on: push

name: python

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Python step
        run: |
          python3 - <<EOF
          import platform
          import sys

          print(f"Python version: '{platform.python_version()}'")
          print(f"Python executable path: '{sys.executable}'")

          x = ${{ toJson(steps) }}
          print(type(x))
          print(x)
          EOF
