on: push

name: python

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Python step
        env:
          STEPS_JSON: ${{ toJson(steps) }}
        run: |
          python3 - <<EOF
          import os
          import json
          import platform
          import sys

          print(f"Python version: '{platform.python_version()}'")
          print(f"Python executable path: '{sys.executable}'")

          job = ${{ toJson(job) }}
          print(f"type of 'job' = '{type(job)}'")
          print("job:", job)

          steps = ${{ toJson(steps) }}
          print(f"type of 'steps' = '{type(steps)}'")
          print("steps:", steps)

          steps_from_env_var = json.loads(os.getenv("STEPS_JSON"))
          print(f"type of 'steps_from_env_var' = '{type(steps_from_env_var)}'")
          print("steps_from_env_var:", steps_from_env_var)
          EOF
