on: push

name: python

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Python step
        run: |
          python3 - <<EOF
          import platform
          import sys

          print(f"Python version: '{platform.python_version()}'")
          print(f"Python executable path: '{sys.executable}'")

          job = ${{ toJson(job) }}
          print(f"type of 'job' = '{type(job)}'")
          print("job:", job)

          steps = ${{ toJson(steps) }}
          print(f"type of 'steps' = '{type(steps)}'")
          print("Steps:", steps)
          EOF
