name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  my-job-B:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create status check
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          script: |
            try {
                // Access the GitHub context
                const context = github.context;
            
                // Log the context to explore its content
                console.log('GitHub Context:', JSON.stringify(context, null, 2));
            
                // Log specific variables
                console.log('Event Name:', context.eventName);
                console.log('Job:', context.job);
                console.log('Workflow:', context.workflow);
                console.log('Action:', context.action);
                console.log('Actor:', context.actor);
                console.log('Repository:', context.repo.repo);
                console.log('Owner:', context.repo.owner);
            
                // Access specific environment variables
                console.log('GitHub Ref:', process.env.GITHUB_REF);
                console.log('GitHub SHA:', process.env.GITHUB_SHA);
                console.log('GitHub Actor:', process.env.GITHUB_ACTOR);
                console.log('GitHub Workflow:', process.env.GITHUB_WORKFLOW);
                console.log('GitHub Action:', process.env.GITHUB_ACTION);
                console.log('GitHub Job:', process.env.GITHUB_JOB);
            
              } catch (error) {
                core.setFailed(`Action failed with error: ${error}`);
              }
            }

            const workflowName = process.env.GITHUB_WORKFLOW;
            const jobName = github.job;
            const eventName = 'github.context.event_name';
            const contextName = `${workflowName} / ${jobName} (${eventName})`;

            const response = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.workflow_run.head_sha,
              state: 'pending', // 'pending', 'success', 'failure' = 'error'
              context: contextName,
              description: 'The job is running',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
            core.setOutput('status_id', response.data.id);
      - name: Run dependent task
        run: echo "Running some task in Workflow B after Workflow A completes successfully."
      # - name: This step will fail
      #   run: exit 1
      - name: Update status to success
        if: success()
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          script: |
            const workflowName = process.env.GITHUB_WORKFLOW;
            const jobName = job.name;
            const eventName = github.context.event_name;
            const contextName = `${workflowName} / ${jobName} (${eventName})`;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.workflow_run.head_sha,
              state: 'success',
              context: contextName,
              description: 'The job succeeded',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
      - name: Update status to failure
        if: failure()
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          script: |
            const workflowName = process.env.GITHUB_WORKFLOW;
            const jobName = job.name;
            const eventName = github.context.event_name;
            const contextName = `${workflowName} / ${jobName} (${eventName})`;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.workflow_run.head_sha,
              state: 'failure',
              context: contextName,
              description: 'The job failed',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
